name: Ludwig CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Basic testing on Ubuntu with Python 3.9
  test:
    runs-on: ubuntu-latest
    name: Core Tests
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify Python environment
      run: |
        python --version
        python -c "import collections.abc; print('✅ Standard library OK')"
        
    - name: Test framework imports
      run: |
        python -c "import sys; sys.path.append('src/frameworks'); import embedded_framework; print('✅ Embedded framework')"
        python -c "import sys; sys.path.append('src/frameworks'); import web_framework; print('✅ Web framework')"
        python -c "import sys; sys.path.append('src/frameworks'); import desktop_framework; print('✅ Desktop framework')"
        
    - name: Test CLI commands
      run: |
        python bin/ludwig help > /dev/null
        python bin/ludwig make:embedded TestDevice
        python bin/ludwig make:pos TestPOS
        python bin/ludwig make:smarthome TestHome
        echo "✅ CLI commands working"
        
    - name: Run integration tests
      run: python tests/test_embedded_integration.py
      
    - name: Check examples exist
      run: |
        test -f examples/embedded/testiot_embedded.ludwig
        test -f examples/embedded/smarthouse_smarthome.ludwig
        test -f examples/embedded/myrobot_robot.ludwig
        echo "✅ Examples exist"

  # Multi-platform testing (simplified)
  platform-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Platform Test ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Test basic functionality
      run: |
        python --version
        python bin/ludwig help
        
    - name: Test framework import
      run: python -c "import sys; sys.path.append('src/frameworks'); import embedded_framework"

  # Documentation check
  docs:
    runs-on: ubuntu-latest
    name: Documentation
    steps:
    - uses: actions/checkout@v3
    
    - name: Check required files
      run: |
        test -f README.md
        test -f CONTRIBUTING.md
        test -f CONTRIBUTORS.md
        test -f CHANGELOG.md
        test -f docs/EMBEDDED_GUIDE.md
        test -f examples/embedded/README.md
        echo "✅ All documentation files exist"
